### ISSUE TITLE
Errors keep occuring on exporting model

### ISSUE THREAD

**Issue by Treehee** [lispascal/lolblender#22] opened 2017-05-07 13:04 UTC
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.78\scripts\addons\io_scene_lol\__bpy_init__.py", line 130, in execute
    VERSION=self.VERSION)
  File "C:\Program Files\Blender Foundation\Blender\2.78\scripts\addons\io_scene_lol\__bpy_init__.py", line 279, in export_char
    lolMesh.exportSKN(meshObj, output_filepath, input_filepath, BASE_ON_IMPORT, VERSION)
  File "C:\Program Files\Blender Foundation\Blender\2.78\scripts\addons\io_scene_lol\lolMesh.py", line 476, in exportSKN
    sknVtx.texcoords[0] = vtxUvs[idx][0]
KeyError: 3088

location: <unknown location>:-1

**Comment by Treehee** [comment] 2017-05-07 13:04
This is the tracebcak from trying to export a custom Renekton skin.

**Comment by Treehee** [comment] 2017-05-10 09:07
Appearently the code is trying to copy UVs from a dictionary with the wrong key. I'll have to check my file if some parts are renamed or something like that. I wouldn't be suprised if they were, considering the way I modelled/weight painted them.

**Comment by Treehee** [comment] 2017-05-17 11:42
There seems to be no issue in my file, just with the exporter :/

**Comment by lispascal** [comment] 2017-07-18 04:58
It's been a while since I've looked at this, but if you could attach the .blend you are trying to export from, I might be able to take a look.

**Comment by Treehee** [comment] 2017-07-18 11:37
[renekton_skin.zip](https://github.com/lispascal/lolblender/files/1155714/renekton_skin.zip)

**Comment by vichound** [comment] 2017-07-20 02:43
Getting the same error even when exporting from the example .blends packed with the plugin, if you need some more info, just ask and I'll get it for you.

**Comment by lispascal** [comment] 2017-07-21 05:28
The cause of the issue appears to be that there is a vertex in the mesh with no UV coordinates (since it is not connected to a face). ca93642 should fix this. Please let me know.

to vic's point, those blends were remnants from the previous iteration of this (on Blender 2.5, as explained in the README's History), and I had not been testing this plugin with those blends (whoops).

With the fix just applied three of those sample blends should work at least; the Nasus blend doesn't conform to the format, so I've removed it from the repository.

**Comment by vichound** [comment] 2017-07-22 21:46
The exporting now pops up this error ([link)](https://gyazo.com/75f7c55f5a48fb8ce2f6bebba80bf848.png), regardless, it still exported the .skn file which I managed to open and view with Wooxy.

However, in all models exported (the wolftest and a Jhin mod in the making) the material name turned into "test" [(link)](https://i.gyazo.com/38cca616e94bd1b82f1bf869da17c265.png), and I assume that's what's causing the game not to read them.

Attempted both with "Base on Imported SKN" option and without.
All attempts of replacing default model with created .skn resulted in error "An essential game asset was not found when loading the game".

If you need more info, just ring me up, thanks for the support.

**Comment by Treehee** [comment] 2017-07-25 12:13
heh. I have no idea how that verticle ended up there.

**Comment by Treehee** [comment] 2017-07-25 12:22
Removing the verticle worked perfectly for the renekton skin :)

I guess the issue can be closed now.

**Comment by lispascal** [comment] 2017-07-29 22:52
@vichound , I'll close this issue (Treehee's); can you open a new issue with an example blend which has the error & the .skn that goes along with it? When you tried "base on imported SKN" did you make sure to input the .skn it is based on?

Thanks

**Closed by lispascal** 2017-07-29 22:52 UTC
